#!/bin/sh
set -eu

# tour41.net entrypoint wrapper
#
# Problem:
#   This stack mounts a persistent volume at /var/www/html so Nginx and php-fpm
#   share the same WordPress files. The upstream WordPress image only copies
#   /usr/src/wordpress -> /var/www/html if /var/www/html is empty.
#   After the first run, updates baked into the image (core/plugins/themes)
#   are masked by the existing volume contents.
#
# Goal:
#   - Keep /var/www/html persistent so WordPress can install additional plugins
#     and themes itself.
#   - Ensure image-baked core/plugins/themes are refreshed when the image is
#     updated.
#   - Preserve user-installed additions in wp-content.

SRC_ROOT="/usr/src/wordpress"
DST_ROOT="/var/www/html"

SRC_MARKER="$SRC_ROOT/.tour41-baked-revision"
DST_MARKER="$DST_ROOT/.tour41-baked-revision"

DST_BAKED_PLUGINS_LIST="$DST_ROOT/wp-content/.tour41-baked-plugins.txt"
DST_BAKED_THEMES_LIST="$DST_ROOT/wp-content/.tour41-baked-themes.txt"

log() {
  printf '%s\n' "tour41-entrypoint: $*" >&2
}

copy_replace() {
  # Replace a destination path with the source path (handles deletions).
  # Usage: copy_replace /src/path /dst/path
  src="$1"
  dst="$2"

  if [ -e "$dst" ] || [ -L "$dst" ]; then
    rm -rf "$dst"
  fi

  # Ensure parent exists
  mkdir -p "$(dirname "$dst")"
  cp -a "$src" "$dst"
}

sync_core_excluding_wp_content() {
  # Remove everything in /var/www/html except wp-content and a few common
  # site-local files, then repopulate core from /usr/src/wordpress.
  #
  # This makes WordPress core update along with the image even when the root
  # directory is backed by a persistent volume.
  log "Refreshing WordPress core into $DST_ROOT (preserving wp-content)"

  mkdir -p "$DST_ROOT"

  # Remove top-level entries except those we must preserve.
  # Note: we keep wp-config.php if present, but it's typically generated by the
  # upstream entrypoint from environment variables.
  for path in "$DST_ROOT"/* "$DST_ROOT"/.*; do
    base="$(basename "$path")"
    case "$base" in
      .|..)
        continue
        ;;
      wp-content|wp-config.php|.htaccess|.user.ini|robots.txt)
        continue
        ;;
    esac
    rm -rf "$path"
  done

  # Copy everything except wp-content from the image source.
  (
    cd "$SRC_ROOT"
    tar -cf - --exclude=./wp-content .
  ) | (
    cd "$DST_ROOT"
    tar -xpf -
  )
}

sync_baked_plugins_and_themes() {
  log "Refreshing baked-in plugins and themes"

  tmp_plugins="$(mktemp)"
  tmp_themes="$(mktemp)"

  # Plugins
  if [ -d "$SRC_ROOT/wp-content/plugins" ]; then
    mkdir -p "$DST_ROOT/wp-content/plugins"
    for item in "$SRC_ROOT"/wp-content/plugins/*; do
      [ -e "$item" ] || continue
      name="$(basename "$item")"
      printf '%s\n' "$name" >> "$tmp_plugins"
      copy_replace "$item" "$DST_ROOT/wp-content/plugins/$name"
    done
  fi

  # Remove plugins that used to be baked-in but are no longer present in the image.
  if [ -f "$DST_BAKED_PLUGINS_LIST" ]; then
    while IFS= read -r old_name; do
      [ -n "$old_name" ] || continue
      if ! grep -Fxq "$old_name" "$tmp_plugins" 2>/dev/null; then
        log "Removing stale baked plugin: $old_name"
        rm -rf "$DST_ROOT/wp-content/plugins/$old_name" || true
      fi
    done < "$DST_BAKED_PLUGINS_LIST"
  fi

  # Themes
  if [ -d "$SRC_ROOT/wp-content/themes" ]; then
    mkdir -p "$DST_ROOT/wp-content/themes"
    for item in "$SRC_ROOT"/wp-content/themes/*; do
      [ -e "$item" ] || continue
      name="$(basename "$item")"
      printf '%s\n' "$name" >> "$tmp_themes"
      copy_replace "$item" "$DST_ROOT/wp-content/themes/$name"
    done
  fi

  # Remove themes that used to be baked-in but are no longer present in the image.
  if [ -f "$DST_BAKED_THEMES_LIST" ]; then
    while IFS= read -r old_name; do
      [ -n "$old_name" ] || continue
      if ! grep -Fxq "$old_name" "$tmp_themes" 2>/dev/null; then
        log "Removing stale baked theme: $old_name"
        rm -rf "$DST_ROOT/wp-content/themes/$old_name" || true
      fi
    done < "$DST_BAKED_THEMES_LIST"
  fi

  # Persist baked lists into the volume for the next run.
  mkdir -p "$DST_ROOT/wp-content"
  sort -u "$tmp_plugins" > "$DST_BAKED_PLUGINS_LIST" 2>/dev/null || :
  sort -u "$tmp_themes" > "$DST_BAKED_THEMES_LIST" 2>/dev/null || :
  rm -f "$tmp_plugins" "$tmp_themes" || true
}

maybe_sync_on_image_update() {
  # If we can't read the marker for some reason, fall back to always syncing.
  src_rev=""
  dst_rev=""

  if [ -f "$SRC_MARKER" ]; then
    src_rev="$(cat "$SRC_MARKER" 2>/dev/null || true)"
  fi
  if [ -f "$DST_MARKER" ]; then
    dst_rev="$(cat "$DST_MARKER" 2>/dev/null || true)"
  fi

  if [ -z "$src_rev" ]; then
    log "WARN: missing source revision marker; forcing sync"
  fi

  if [ "$src_rev" != "$dst_rev" ]; then
    log "Detected image update (src=$src_rev dst=$dst_rev); syncing"
    sync_core_excluding_wp_content
    sync_baked_plugins_and_themes

    # Persist the marker into the volume.
    if [ -f "$SRC_MARKER" ]; then
      cp -f "$SRC_MARKER" "$DST_MARKER" || true
    fi

    # Ensure php-fpm can read the files.
    if command -v chown >/dev/null 2>&1; then
      chown -R www-data:www-data "$DST_ROOT" || true
    fi
  else
    log "Image revision unchanged; skipping sync"
  fi
}

maybe_sync_on_image_update

# Hand off to the official WordPress entrypoint (config generation, etc.)
exec docker-entrypoint.sh "$@"
